name: myhb_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core:
  firebase_auth:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/



  fonts:
    - family: Gelasio
      fonts:
        - asset: fonts/Gelasio.ttf
    - family: Nunito
      fonts:
        - asset: fonts/Nunito.ttf

